# Generated by Django 5.1.1 on 2024-12-02 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sections',
            name='course',
        ),
    ]
