# Generated by Django 5.1.1 on 2024-12-08 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsCourseL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semister', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=255)),
                ('teacher', models.CharField(max_length=255)),
                ('course_status', models.CharField(choices=[('ongoing', 'Ongoing'), ('pass', 'Pass'), ('fall', 'Fall'), ('withdraw', 'Withdraw'), ('complete', 'Complete'), ('enroll', 'Enroll')], default='enroll', max_length=255)),
                ('course_fee', models.FloatField(blank=True, default=0, null=True)),
                ('course_payment', models.BooleanField(blank=True, default=False, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students')),
            ],
        ),
    ]
