# Generated by Django 5.1.1 on 2024-12-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_studentscoursel_studentscourselist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentscourselist',
            name='semister',
            field=models.DateField(max_length=255),
        ),
    ]
