# Generated by Django 5.1.1 on 2024-12-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_studentscourselist_semister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentscourselist',
            name='semister',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
