# Generated by Django 5.1.1 on 2024-12-09 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseSection', '0002_coursesection_teacher'),
        ('students', '0005_alter_studentscourselist_semister'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentscourselist',
            name='course_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CourseSection.coursesection'),
        ),
    ]
