# Generated by Django 5.1.1 on 2024-12-09 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_studentscourselist_course_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentscourselist',
            name='course_section',
        ),
    ]
