# Generated by Django 5.1.1 on 2024-12-09 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_remove_sections_course'),
        ('students', '0007_remove_studentscourselist_course_section'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentscourselist',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.sections'),
        ),
        migrations.AlterField(
            model_name='studentscourselist',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teachers'),
        ),
    ]
