# Generated by Django 5.1.1 on 2024-12-02 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('sections', '0002_remove_sections_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.sections')),
            ],
        ),
    ]
